version: "3.9"

# Use a named network with an explicit name to avoid project-prefixing
networks:
  rag-master:
    name: rag-master
    driver: bridge

# Define named volumes with explicit names to avoid project prefixes
volumes:
  rag-chromadb-data:
    name: rag-chromadb-data
  rag-websearch-config:
    name: rag-websearch-config
  rag-vllm-cache:
    name: rag-vllm-cache
  rag-ingestion-data:
    name: rag-ingestion-data

services:
  rag-backend:
    build: ./rag-backend
    image: rag-backend:latest        # explicit image name
    container_name: rag-backend     # explicit container name
    networks:
      - rag-master
    ports:
      - "8000:8000"
    depends_on:
      - rag-ocr
      - rag-vision
      - rag-embedder
      - rag-ner
      - rag-websearch
      - rag-vllm
      - rag-chromadb

  rag-ingestion:
    build: ./rag-ingestion
    image: rag-ingestion:latest
    container_name: rag-ingestion
    networks:
      - rag-master
    volumes:
      - rag-ingestion-data:/data
    expose:
      - "8000"

  rag-ocr:
    build: ./rag-ocr
    image: rag-ocr:latest
    container_name: rag-ocr
    networks:
      - rag-master
    expose:
      - "8000"

  rag-vision:
    build: ./rag-vision
    image: rag-vision:latest
    container_name: rag-vision
    networks:
      - rag-master
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    expose:
      - "8000"

  rag-embedder:
    build: ./rag-embedder
    image: rag-embedder:latest
    container_name: rag-embedder
    networks:
      - rag-master
    expose:
      - "8000"

  rag-ner:
    build: ./rag-ner
    image: rag-ner:latest
    container_name: rag-ner
    networks:
      - rag-master
    expose:
      - "8000"

  rag-websearch:
    build: ./rag-websearch
    image: rag-websearch:latest
    container_name: rag-websearch
    networks:
      - rag-master
    volumes:
      - rag-websearch-config:/etc/searxng
    expose:
      - "8080"

  rag-vllm:
    build: ./rag-vllm
    image: rag-vllm:latest
    container_name: rag-vllm
    networks:
      - rag-master
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - rag-vllm-cache:/root/.cache
    expose:
      - "8000"

  rag-webui:
    build: ./rag-webui
    image: rag-webui:latest
    container_name: rag-webui
    networks:
      - rag-master
    ports:
      - "8501:8501"
    depends_on:
      - rag-backend

  rag-chromadb:
    build: ./rag-chromadb
    image: rag-chromadb:latest
    container_name: rag-chromadb
    networks:
      - rag-master
    volumes:
      - rag-chromadb-data:/data
    expose:
      - "8000"
