name: "clip"
platform: "onnx"
max_batch_size: 32
input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  },
  {
    name: "text"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]
output [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]